# Generated by Django 5.0.6 on 2024-07-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
