# Generated by Django 5.0.6 on 2024-07-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0002_alter_formdata_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='STPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('stp_id', models.IntegerField(unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=255)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('active_ingredient_concentration', models.CharField(max_length=255)),
                ('capsule_size', models.CharField(max_length=255)),
                ('dissolution_test', models.CharField(max_length=255)),
                ('hardness_test', models.CharField(max_length=255)),
                ('moisture_content', models.CharField(max_length=255)),
                ('uniformity_of_dosage_unit', models.CharField(max_length=255)),
                ('appearance', models.CharField(max_length=255)),
                ('packaging_integrity', models.CharField(max_length=255)),
                ('storage_conditions', models.CharField(max_length=255)),
                ('stability_testing', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
