# Generated by Django 5.0.6 on 2024-07-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0003_stprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stprecord',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stprecord',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
